polls/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static

app_name = 'polls'
urlpatterns = [
    path('', views.index),
    path('home/', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('my-stacks/', views.my_stack, name='works'),
    path('my-stacks/<slug:category_slug>/', views.my_project, name='project'),
    path('my-stacks/<slug:category_slug>/<slug:project_slug>/', views.project_detail, name='project_detail'),    
    path('contact/', views.contact, name='contact'),
    path('post-json/', views.post_json, name='post-json'),
    path('error/', views.error_page, name='error'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls'))
   
]

polls/models.py
from django import forms
from django.db import models

class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    img = models.ImageField(upload_to='images/')
    
    def __str__(self):
        return self.title
        
    class Meta:
        ordering = ('title',)

class Project(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now=True)
    proj_link = models.URLField(null=True, blank=True)  # needed for itchio widget
    proj_embed_link = models.URLField(null=True, blank=True)  # needed for itchio widget
    proj_playable_link = models.URLField(null=True, blank=True)  # webGL playable version of itchio widget
    slug = models.SlugField(unique=True)
    images = models.ImageField(upload_to='images/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title
        
    class Meta:
        ordering = ('created',)

class ProjectImages(models.Model):
    project = models.ForeignKey(Project, default=None, on_delete=models.CASCADE)
    images = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.project.title
    
class ContactForm(forms.Form):
    person_name = forms.CharField(max_length=50)
    from_email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

class DocTag(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class UploadDocument(models.Model):
    name = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now=True)
    tag = models.ForeignKey(DocTag, on_delete=models.CASCADE)
    file = models.FileField(upload_to='pdfs/')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)

class About_detail(models.Model):
    greeting = models.TextField(null=True, blank=True)  # Short introduction
    detail = models.TextField(null=True, blank=True)  # Motivation letter
    image = models.ImageField(upload_to='images/')
    email = models.EmailField(null=True, blank=True)
    mobile = models.TextField()
    linkedin = models.TextField(null=True, blank=True) 
    github = models.TextField(null=True, blank=True)

polls/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from .models import About_detail, Category, Project, ProjectImages, UploadDocument
from django.core.mail import BadHeaderError, send_mail
from django.http.response import JsonResponse

def index(request):
    cat = Category.objects.all()
    for_frontend = {
        'category': cat,
    }
    return render(request,'polls/index.html', for_frontend)

def about(request):
    try:
        ad = About_detail.objects.first()
        cat = Category.objects.all()
        doc = UploadDocument.objects.get(name="CV").file
        for_frontend = {
            'ad': ad,
            'category': cat,
            'doc_cv': doc,
        }
        return render(request,'polls/about.html', for_frontend)
    except FileNotFoundError as e:
        return error_page(request)
    except FileExistsError as e:
        return error_page(request)
    except Exception as e:
         return error_page(request)

def my_stack(request):
    cat = Category.objects.all()
    for_frontend = {
        'category': cat,
    }
    return render(request,'polls/mywork.html', for_frontend)

def my_project(request, category_slug):
    cat = Category.objects.all()
    unique_slug = Category.objects.get(slug = category_slug)
    project = Project.objects.all()
    
    def get_project(a, b):
     for item in a:
        if(b == item.category):
            return item
   
    check_cat = get_project(project, unique_slug)

    for_frontend = {
        'post': unique_slug,
        'category': cat,
        'project': project,
        'check': check_cat,
    }
    
    return render(request, 'polls/project.html', for_frontend)

def project_detail(request, category_slug, project_slug):
    project = Project.objects.get(slug=project_slug)
    cat = Category.objects.all()
    project_images = ProjectImages.objects.filter(project=project)

    for_frontend = {
        'project': project,
        'category': cat,
        'project_images': project_images
    }
    return render(request, 'polls/project_detail.html', for_frontend)


def contact(request):
    cat = Category.objects.all()
    for_frontend = {
        'category': cat,
    }
    if request.POST:
        contact_list = []
        request_data = request.POST
        for data in request_data.values():
            contact_list.append(data)
        Pname = contact_list[1]
        from_email = contact_list[2]
        subject = contact_list[3]
        message = contact_list[4] 
        try:
            send_mail(Pname+" - "+subject, message +"\nFrom : "+from_email, None, [' """your email address which receive others messages """ '], fail_silently=False)
        except BadHeaderError:
            return HTTPResponse('Invalid header found.')
        
    return render(request,'polls/contact.html', for_frontend)

def post_json(request):
    #  data = list(AImages.objects.values()) + list(Category.objects.values())
    return render(request,'polls/about.html')
    #  return JsonResponse(data, safe=False)

def error_page(request):
    return render(request, 'polls/error.html')

polls/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/css/splide.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js"></script>
        <script src="{% static 'js/myjs.js'%}"></script>       
        <title>Kpoke's Keeper</title>
    </head>
    <body>
        <div class="navbar-fixed">
            <nav class="nav-extended">
                <div class="nav-wrapper">
                    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
                    <ul class="left hide-on-med-and-down">
                        <li>
                            <a href="{% url 'polls:home' %}" class="logo_link">
                               <i class="material-icons">home</i>
                            </a>
                        </li>
                        <li><a href="{% url 'polls:about' %}" class="flow-text">About me</a></li>
                        <li><a class="dropdown-trigger flow-text" href="{% url 'polls:works' %}" data-target="myworks_dropdown">Stacks<i class="material-icons right">arrow_drop_down</i></a></li>   
                    </ul>
                </div>
            </nav>
        </div>
        <ul id="myworks_dropdown" class="dropdown-content">
            {% for item in category %}
                <li><a id="cat_title"href="{% url 'polls:works' %}{{ item.slug }}">{{ item.title }}</a></li>
            {% endfor %}
            
        </ul>
        <ul class="sidenav" id="mobile-demo">
            <li>
                <a href="#" id="logo" class="flow-text">Kpoke's Keeper</a>
            </li>
            <li><a href="{% url 'polls:home' %}"><i class="material-icons">home</i>Home</a></li>
            <li><a href="{% url 'polls:about' %}"><i class="material-icons">people</i>About me</a></li>
            <li><a href="{% url 'polls:works' %}"><i class="material-icons">computer</i>Stacks</a></li>
        </ul>
        <div id="spinner-box">
            <div class="container center">
                <div class="preloader-wrapper big active">
                    <div class="spinner-layer spinner-blue-only">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div>
                        <div class="gap-patch">
                            <div class="circle"></div>
                        </div>
                        <div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                </div>
            </div>
       </div>
    <div id="data-box" class="not-visible">
    {% block content %}

    {% endblock content %}
    </div>
    <footer class="page-footer">
        <div class="footer-copyright">
          <div class="container">
            <div id="footer-text" class="flow-text">© {% now "Y" %} Made by David Kohalmi</div>
          </div>
        </div>
      </footer>
    </body>
</html>

polls/templates/polls/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <h1 id ="greetingId" class="flow-text">Hello, my name is Kőhalmi Balázs Dávid</h1>
    <div class="row">
        <div class="col s12 center">   
            <p id="about-me-text">
                {{ ad.greeting }}
            </p>
        </div>
    </div>
    <div class="row"> 
        <div class="col s12 center">   
            <img id="picsofme" class="responsive-img" src="{{ ad.image.url }}"></img>
        </div>
    </div>
    <div class="row">
        <div class="col s12 center">
            <ul id="info">
                <li>
                    <i class="small material-icons">email</i>
                    <span class="flow-text">{{ ad.email }}</span>
                </li>
                <li>
                    <i class="small material-icons">call</i>
                    <span class="flow-text">{{ ad.mobile }}</span>
                </li>
                <li>
                    <a target="_blank" href="{{ ad.github }}">
                        <img id="link-github" src="{% static 'images/GitHub-Mark.png'%}" alt="github"></img>
                    </a>
                    <a target="_blank" href="{{ ad.linkedin }}">
                        <img id="link-linkedin" src="{% static 'images/Li-In-Bug.png'%}" alt="linkedin"></img>
                    </a>
                </li>
            </ul>   
        </div>
    </div>
    <div class="row">
        <div class="col s12">
            <p id="about-me-text">
                {{ ad.detail }}
            </p>
        </div>
        <div class="col s12 center">
            <button class="btn waves-effect waves-light btn-large" type="submit">
                <i class="material-icons right">receipt</i>
               <a id="cv-link"  href="{{ doc_cv.url }}" download>Download CV</a>
            </button>
        </div>
    </div>
</div>

{% endblock content%}

polls/templates/polls/error.html
{% extends "base.html" %}

{% block content %}

<h1>Something went wrong... </h1>

{% endblock content%}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block content %}
<div id="canvasText">
    <h1 class="z-depth-4">Welcome.</h1>
</div>
<div id="#myCanvas"></div>

<script type="module">

    import * as THREE from 'https://cdn.skypack.dev/three';
    import { OrbitControls } from 'https://cdn.skypack.dev/pin/three@v0.133.1-dCIBIz3pnzocx0lNrLHe/mode=imports/unoptimized/examples/jsm/controls/OrbitControls.js';
    import { Lensflare, LensflareElement } from 'https://cdn.skypack.dev/pin/three@v0.133.1-dCIBIz3pnzocx0lNrLHe/mode=imports/unoptimized/examples/jsm/objects/Lensflare.js';

    let container;
    let camera, scene, renderer;
    let controls;
    let width = window.innerWidth;
    let height = window.innerHeight / 1.1;

    const clock = new THREE.Clock();
    
    init();
    animate();

    function init() {
        container = document.getElementById("#myCanvas");
        
        // camera
        camera = new THREE.PerspectiveCamera( 40, width / height, 1, 15000 );
        camera.position.z = 100;

        // scene
        scene = new THREE.Scene();
        scene.background = new THREE.Color().setHSL( 0.51, 0.4, 0.01 );
        scene.fog = new THREE.Fog( scene.background, 3500, 15000 );

        // world
        //#region 
        const s = 200;

        const geometry = new THREE.BoxGeometry(s, s, s);
        const material = new THREE.MeshPhongMaterial({ color: 0xffffff, specular: 0xffffff, shininess: 50 });

        for ( let i = 0; i < 2000; i ++ ) {

            const mesh = new THREE.Mesh(geometry, material);

            mesh.position.x = 8000 * (2.0 * Math.random() - 1.0);
            mesh.position.y = 8000 * (2.0 * Math.random() - 1.0);
            mesh.position.z = 8000 * (2.0 * Math.random() - 1.0);

            mesh.rotation.x = Math.random() * Math.PI;
            mesh.rotation.y = Math.random() * Math.PI;
            mesh.rotation.z = Math.random() * Math.PI;

            mesh.matrixAutoUpdate = false;
            mesh.updateMatrix();

            scene.add(mesh);

        }
        
        const gem = new THREE.SphereGeometry(1,1,1);
        const sphere = new THREE.Mesh(gem, material);
        sphere.position.x = 5000;
        sphere.position.y = 0;
        sphere.position.z = -1000;
        sphere.matrixAutoUpdate = false;
        sphere.updateMatrix();
        scene.add(sphere);

        camera.lookAt(sphere.position);
        //#endregion

        // lights
        const dirLight = new THREE.DirectionalLight( 0x16E3F3, 0.5 );
        dirLight.position.set( 0, -1, 0 ).normalize();
        scene.add( dirLight );
        //#endregion

        // renderer
        //#region 
        renderer = new THREE.WebGLRenderer( {container, alpha:true, antialias: true } );
        renderer.setPixelRatio( window.devicePixelRatio );
        renderer.setSize(width, height);
        renderer.outputEncoding = THREE.sRGBEncoding;
        container.appendChild( renderer.domElement );
        //#endregion

        // Controls
        //#region 
        controls = new OrbitControls(camera, renderer.domElement);
        controls.enabled = false;
        controls.autoRotate = true;
        controls.autoRotateSpeed = -1;
        controls.domElement = container;
        controls.target = sphere.position; 
        //#endregion

        // events
        window.addEventListener( 'resize', onWindowResize );
    }

    function onWindowResize() {
        renderer.setSize(width, height);
        camera.aspect = width / height;
        camera.updateProjectionMatrix();
    }

    function animate() {
        requestAnimationFrame( animate );
        render();
    }

    function render() {
        const delta = clock.getDelta();
        controls.update();
        renderer.render(scene, camera);

    }
</script>
{% endblock content%}

polls/templates/polls/mywork.html
{% extends "base.html" %}

{% block content %}

<div id="cont" class="row">
  <div class="center">
  {% for topic in category %}
  <div class="col s6 m3 l2 xl1">
      <div class="card hoverable">
        <a href="{{ topic.slug }}"> 
          <img class="responsive-img materialboxed" src="{{ topic.img.url }}" alt="pics">
          <div class="card-content flow-text">
              {{ topic.title }}
          </div>
        </a>
      </div>
    </div>
    {% endfor %}
    </div>
  </div>

{% endblock content%}

polls/templates/polls/project.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
    <h1 class="header">{{post}}</h1>
        {% if check %}
            {% for proj in project %}
                {% if proj.category == post %}
                    <div class="col s12 m6 l4 xl2">
                        <div class="card hoverable">
                            <div class="card-image waves-effect waves-block waves-light">
                                <a href="{{ proj.slug }}">
                                    <img class="responsive-img materialboxed" src="{{ proj.images.url }}" alt="picss">
                                </a>
                            </div>
                            
                            <div class="card-reveal flow-text">
                                <span class="card-title grey-text text-darken-4">{{ proj.title }}</span>
                                <p style="color:#26a69a;">{{ proj.description }}</p>
                            </div>
                            <div class="card-content flow-text"> 
                                <span class="card-title activator grey-text text-darken-4">{{ proj.title }}<i class="material-icons right">more_vert</i></span>
                                <a href="{{ proj.slug }}">Details</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
        <div class="container">
            <h4 id="no-project-error" class="flow-text" >Currently no project available</h4>
        </div>
        {% endif %}
    </div>
{% endblock %}

polls/templates/polls/project_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <h1 class="header">{{ project.title }}</h1>
            <div class="col s12 center">
                <p class="flow-text">
                    {{ project.description }}
                </p>
            <div class="col s12">
                <div class="splide">
                    <div class="splide__track">
                        <ul class="splide__list ">
                            {% for image in project_images %}
                                <li class="splide__slide center">
                                    <img src="{{ image.images.url }}">
                                </li>
                            {% endfor %}               
                        </ul>
                    </div>
                    <div class="splide__progress">
                        <div class="splide__progress__bar">
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
        <div class="divider"></div>
        <br>
        {% if project.proj_link %}
        <div class="row">
            <div class="col s12">
                <div class="video-container">
                    <iframe frameborder="0" src="{{ project.proj_embed_link}}"><a href="{{ project.proj_link }}"></a></iframe>
                </div>
            </div>
            {% if project.proj_playable_link %}
            <div class="col s12">
                <div class="video-container">
                    <iframe frameborder="0" src="{{ project.proj_playable_link}}" allowfullscreen=""><a href="{{ project.proj_link }}"></a></iframe>
                </div>
            </div>
            {% endif %}
        </div>
        {% endif %}
        
    </div>
    
{% endblock %}